# SwiftLint configuration for RuneKit
# Enforces Swift style and conventions

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift

# Analyzer rules (require compilation)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments during development
  - line_length # Handled by SwiftFormat
  - file_header # Disabled during initial development
  - sorted_imports # Can be enabled later
  - trailing_comma # Personal preference
  - file_name # Demo files contain multiple functions, not types

# Rule configurations
line_length:
  warning: 120
  error: 150

file_length:
  warning: 600
  error: 800

function_body_length:
  warning: 75
  error: 150

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 350
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50



# Custom rules (disabled for initial development)
# These can be enabled later as the codebase matures
# custom_rules:
#   # Require documentation for public APIs
#   public_docs:
#     name: "Public Documentation"
#     regex: '^public (?!init)(?!deinit)(?!subscript)(?!operator)(?!enum)(?!struct)(?!class)(?!protocol)(?!typealias)(?!var)(?!let)(?!func).*\n(?!.*///)(?!.*\*)'
#     message: "Public declarations should be documented"
#     severity: warning
#
#   # Prefer explicit self for clarity in actors
#   actor_self:
#     name: "Actor Self Reference"
#     regex: 'actor\s+\w+.*\{[\s\S]*?(?<!self\.)\w+\s*\('
#     message: "Consider using explicit self in actor methods for clarity"
#     severity: warning
#
#   # Ensure proper ANSI escape sequence format
#   ansi_format:
#     name: "ANSI Escape Sequence Format"
#     regex: '\\u\{001B\}\[(?![0-9;]*[A-Za-z])'
#     message: "ANSI escape sequences should follow proper CSI format"
#     severity: error

# File header template (disabled for initial development)
# file_header:
#   required_pattern: |
#                     \/\/ .*\.swift
#                     \/\/ RuneKit
#                     \/\/
#                     \/\/ Created by .* on .*\.
#                     \/\/ Copyright © \d{4} .* All rights reserved\.
#   forbidden_pattern: |
#                      \/\/ Created by Xcode
